apiVersion: apps/v1
kind: Deployment
metadata:
  name: TEMPLATE_NAMESPACE 
  namespace: {{ .Release.Namespace }}
  labels:
    app: TEMPLATE_NAMESPACE 
spec:
  selector:
    matchLabels:
      app: TEMPLATE_NAMESPACE 
  replicas: 1
  template:
    metadata:
      labels:
        app: TEMPLATE_NAMESPACE 
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: TEMPLATE_NAMESPACE 
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {{ toYaml .Values.resources | nindent 10 }}
      terminationGracePeriodSeconds: 30