apiVersion: v1
kind: Service
metadata:
  labels:
    app: TEMPLATE_NAMESPACE 
  name: TEMPLATE_NAMESPACE 
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: TEMPLATE_NAMESPACE 
  sessionAffinity: None
  type: ClusterIP
