# permissions for end users to view componentplans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: componentplan-viewer-role
rules:
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - componentplans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - componentplans/status
  verbs:
  - get
