# permissions for end users to edit portals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portal-editor-role
rules:
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - portals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - portals/status
  verbs:
  - get
