# permissions for end users to view portals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portal-viewer-role
rules:
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - portals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - portals/status
  verbs:
  - get
