# permissions for end users to edit ratings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rating-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: core
    app.kubernetes.io/part-of: core
    app.kubernetes.io/managed-by: kustomize
  name: rating-editor-role
rules:
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - ratings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - ratings/status
  verbs:
  - get
