---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - repositories/finalizers
  verbs:
  - update
- apiGroups:
  - core.kubebb.k8s.com.cn
  resources:
  - repositories/status
  verbs:
  - get
  - patch
  - update
