apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: ComponentPlan
metadata:
  name: sub-wordpress-sample-repository-bitnami-sample.wordpress-16.1.9
  namespace: default
spec:
  approved: true
  component:
    name: repository-bitnami-sample.wordpress
    namespace: kubebb-system
  version: 16.1.9
