apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: Subscription
metadata:
  name: wordpress-sample
  namespace: default
spec:
  component:
    name: repository-bitnami-sample.wordpress
    namespace: kubebb-system
  componentPlanInstallMethod: auto
