apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: only-helm-lint-pipeline
  annotations:
    tekton.dev/displayName: "component-rbac-gen"
    tekton.dev/platforms: "linux/amd64"
  namespace: kubebb-system
spec:
  description: >-
    convert image to base64
  params:
    - name: COMPONENT_NAME
      description: >-
        component name
    - name: REPOSITORY_NAME
      description: repository name
      default: "kubebb"
    - name: VERSION
      description: component version
    - name: URL
      description: the full URL of the component tgz file.
  results:
  - name: HELM_LINT
    value: $(tasks.helm-lint.results.LINT)
  tasks:
    - name: helm-lint
      retries: 2
      taskRef:
        resolver: cluster
        params:
        - name: kind
          value: task
        - name: name
          value: helm-lint
        - name: namespace
          value: kubebb-system
      params:
        - name: url
          value: $(params.URL)
        - name: component
          value: $(params.COMPONENT_NAME)
        - name: version
          value: $(params.VERSION)
