apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-lint
  namespace: kubebb-system
spec:
  params:
  - name: url
    type: string
  - name: component
    type: string
  - name: version
    type: string
  results:
  - name: LINT
    type: string
  steps:
    - name: helm-lint
      image: kubebb/rating:v0.1.3
      script: |
        #!/usr/bin/env sh
        # Download and untar chart package
        helm pull --untar $(params.url)
        #tar -zxvf $(params.component)-$(params.version).tgz

        helm lint ./$(params.component)
        echo $? | tee $(results.LINT.path)
